# Generated by Django 6.0.2 on 2026-02-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_author_bio_alter_edition_date_alter_story_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
