# Generated by Django 6.0.2 on 2026-02-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_story_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
