# Generated by Django 6.0.2 on 2026-02-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_author_bio_alter_story_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'verbose_name': 'Edition', 'verbose_name_plural': 'Editions'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
