# Generated by Django 6.0.2 on 2026-02-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_author_options_alter_edition_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
